import {ITabledata} from './table';
export const TableData: ITabledata[] =  [
{
    txdate: '11/21/2019',
    th: "7",
    surface: 'test surface 1',
    code: 'MSD',
    procedure: 'Missing Tooth 1',
    plantype: 'General',
    visit : 1,
    status: 'Accepted',
    provider: 'test provider 1',
    office: 'bangalore',
    dos: 'test dos 1',
},
{
    txdate: '12/21/2019',
    th: "7",
    surface: 'test surface  2',
    code: 'BHJ',
    procedure: 'Missing Tooth 2',
    plantype: 'Hygiene',
    visit : 2,
    status: 'Completed',
    provider: 'test provider 2',
    office: 'chennai',
    dos: 'test dos 2',
},
{
    txdate: '10/22/2019',
    th: "2",
    surface: 'test surface  3',
    code: 'BJJ',
    procedure: 'Missing Tooth 3',
    plantype: 'Hygiene',
    visit : 1,
    status: 'Deleted',
    provider: 'test provider 3',
    office: 'hyderabad',
    dos: 'test dos 3',
},
{
    txdate: '04/10/2019',
    th: "4",
    surface: 'test surface  4',
    code: 'MXAA',
    procedure: 'Missing Tooth 4',
    plantype: 'General',
    visit : 2,
    status: 'Referred',
    provider: 'test provider 4',
    office: 'chennai',
    dos: 'test dos 4',
},
{
    txdate: '05/21/2019',
    th: "8",
    surface: 'test surface 5',
    code: 'ZBDE',
    procedure: 'Missing Tooth 5',
    plantype: 'Hygiene',
    visit : 2,
    status: 'Completed',
    provider: 'test provider 5',
    office: 'chennai',
    dos: 'test dos 5',
},
{
    txdate: '09/21/2019',
    th: "7",
    surface: 'test surface 6',
    code: 'PUXM',
    procedure: 'Missing Tooth 6',
    plantype: 'Hygiene',
    visit : 2,
    status: 'Completed',
    provider: 'test provider 6',
    office: 'chennai',
    dos: 'test dos 6',
},
{
    txdate: '11/21/2019',
    th: "10",
    surface: 'test surface 7',
    code: 'ATSU',
    procedure: 'Missing Tooth 7',
    plantype: 'Hygiene',
    visit : 2,
    status: 'Unaccepted',
    provider: 'test provider 7',
    office: 'cochin',
    dos: 'test dos 7',
},
{
    txdate: '12/21/2019',
    th: "7",
    surface: 'test surface 8',
    code: 'DJSK',
    procedure: 'Missing Tooth 8',
    plantype: 'Hygiene',
    visit : 2,
    status: 'Proposed',
    provider: 'test provider 8',
    office: 'bangalore',
    dos: 'test dos 8',
},
{
    txdate: '01/10/2019',
    th: "15",
    surface: 'test surface 9',
    code: 'IOSK',
    procedure: 'Missing Tooth 9',
    plantype: 'General',
    visit : 1,
    status: 'Existing',
    provider: 'test provider 9',
    office: 'chennai',
    dos: 'test dos 9',
},
{
    txdate: '09/21/2019',
    th: "7",
    surface: 'test surface 10',
    code: 'ATHSS',
    procedure: 'Missing Tooth 10',
    plantype: 'Hygiene',
    visit : 20,
    status: 'Existing',
    provider: 'test provider 10',
    office: 'chennai',
    dos: 'test dos 10',
}
]